Re-scss absensi component
blibli-future/athens-ui pull request #10
Opened 2017-06-30 04:50 UTC by aamesaa

Rename absesnsi component and add data binding.

2017-06-30 10:12 UTC, riencus requested changes
There's some class naming problem and the usage of vue component that needs some discussion first.

2017-06-30 10:12 UTC, riencus commented on src/component/LoginForm.vue
> +  .login {
I think you forgot to use the class, CMIIW I don't see any `class="login"` anywhere

2017-06-30 10:12 UTC, riencus commented on src/component/absensi/Employee.vue
> +        </table>
This is minor, but I think the mis-indentation on `</table>` is annoying

2017-06-30 10:12 UTC, riencus commented on src/component/absensi/Upload.vue
> +            &[type=file]{
Why use this selector? Since I don't see any other tag using `upload__input` class, why don't we insert `border: none` into the `upload__input` class?

2017-06-30 10:12 UTC, riencus commented on src/component/absensi/employee/TableEmp.vue
>  </template>
If this class only contains a `<tr>` tag, why don't we just delete this class and use `v-for` on the `Employee.vue` directly?
```
<tr v-for="employee in employees">
        <td>{{employee.nik}}</td>
        <td>{employee.fullname}}</td>
        ...
</tr>
```
Or... if We want to make it separate, how about make the whole table to be included inside this file?
```
<template>
    <table>
    ....
    </table>
</template>
````

2017-06-30 10:12 UTC, riencus commented on src/component/absensi/shift/NewShift.vue
> +                <label for="department" class="newShift__form__section__label"> Department</label>
Bem naming [doesn't recommend](http://getbem.com/faq/#css-nested-elements) Us to use `block__element__element...` We should change the class name.
How about `new-shift__label`?

2017-06-30 10:12 UTC, arielchristianto commented on src/component/absensi/shift/Shift.vue
> +                    :item="item">
These two attributes (`key` and `item`) are unnecessary; only to be used when `v-for`  is [used on a component](https://vuejs.org/v2/guide/list.html#Components-and-v-for)

2017-06-30 10:12 UTC, arielchristianto commented on src/component/absensi/shift/Shift.vue
> +                }
How about `shift__column:hover { ... } `? It's more BEM friendly and has more direct meaning in my opinion.

2017-06-30 10:59 UTC, aamesaa commented on src/component/LoginForm.vue
> +  .login {
Ok. I think I've missed that.

2017-06-30 10:59 UTC, aamesaa commented on src/component/absensi/employee/TableEmp.vue
>  </template>
At first, the whole table was separated, but after I use `v-for` it also loop the `<thead>`. So, i separated the component inside of `<tbody>`. Should we directly use `v-for` or separate the table component?

2017-06-30 10:59 UTC, aamesaa commented on src/component/absensi/shift/NewShift.vue
> +                <label for="department" class="newShift__form__section__label"> Department</label>
I changed it into `new-shift__label`, `new-shift__input` and `new-shift__section`

2017-06-30 11:02 UTC, arielchristianto commented on src/component/absensi/employee/TableEmp.vue
>  </template>
Let's discuss it. First, I want to know why did you separate the table in the first place. Why did you separate them?

2017-06-30 12:44 UTC, aamesaa commented on src/component/absensi/employee/TableEmp.vue
>  </template>
my bad. I just realize that i've directly use `v-for` in `Shift.vue`. Gonna change it soon

2017-07-01 17:24 UTC, aamesaa commented on src/component/absensi/shift/Shift.vue
> +                }
I removed the `table-hover`, and add `table__body` to put the `tr:hover`

2017-07-01 17:26 UTC, aamesaa commented on src/component/absensi/shift/Shift.vue
> +                    :item="item">
in the shift page, we need to get the nik for updating the TapIn / TapOut. I think I missplace and using the wrong syntax. I have fix it in the last commit

2017-07-02 05:55 UTC, aamesaa commented
All the requested change have been committed

2017-07-02 10:43 UTC, arielchristianto commented on src/component/absensi/shift/Shift.vue
> +                    :item="item">
@aamesaa the `:key="item.id" :item="item">`is still there, does it breaks the whole system when those 2 is not removed?

2017-07-02 10:45 UTC, arielchristianto commented on src/component/absensi/shift/Shift.vue
> +                }
why not make a class just for `<tr>` instead of giving `:hover` into the `<tr>` tag?

2017-07-02 13:10 UTC, aamesaa commented on src/component/absensi/shift/Shift.vue
> +                    :item="item">
My bad. I thought this was Presensi page, so I said that we need `:key="item.id" :item="item"` and made a change on `Presensi.vue`. I've been fixed this on the latest commit

2017-07-02 15:19 UTC, riencus approved these changes

2017-07-02 15:20 UTC, merged