Re scss report
blibli-future/athens-ui pull request #12
Opened 2017-07-08 03:51 UTC by aamesaa

This PR is about rename the class in Report page using BEM standart. In this pull request, the download button is worked, it can download the table in HTML into a .csv file

2017-07-08 07:18 UTC, sebastianbagya approved these changes
OK

2017-07-08 07:51 UTC, riencus requested changes

2017-07-08 07:51 UTC, arielchristianto commented on src/component/Report.vue
> +                }})
`this.mulai` & `this.selesai`? Where does it come from? I don't see any assignment to both of those field

2017-07-08 07:51 UTC, arielchristianto commented on src/component/Report.vue
> +              var downloadLink;
I just want to point up the fact that there is an inconsistency on the method naming style. Please change it to `camelCase`

2017-07-08 08:32 UTC, aamesaa commented on src/component/Report.vue
> +                }})
I refactored the `v-model` into `startDate` and `endDate`. Already fix it

2017-07-09 15:07 UTC, riencus requested changes

2017-07-09 15:07 UTC, arielchristianto commented on src/component/Report.vue
>            	var csv = [];
You forgot to `camelCase` this one

2017-07-09 16:07 UTC, aamesaa commented
All requested changed have been committed

2017-07-09 16:13 UTC, riencus approved these changes

2017-07-10 00:36 UTC, merged